(in-package :minerva.gui)

(%deftest test-filler-pushes-siblings-no-spacing
  (let* ((left (make-instance 'color-rect :min-width 100 :min-height 40))
         (middle (make-instance 'filler :min-width 0 :min-height 0 :expand-x t :expand-y nil))
         (right (make-instance 'color-rect :min-width 100 :min-height 40))
         (box (make-instance 'hbox :children (list left middle right) :spacing 0))
         (root (make-instance 'window :width 500 :height 100 :child box)))
    (%assert-min-size box 200 40 "filler no-spacing min-size")
    (layout root (make-rect :x 0 :y 0 :width 500 :height 100))
    (%assert-rect left 0 0 100 40 "filler no-spacing left")
    (%assert-rect middle 100 0 300 0 "filler no-spacing middle")
    (%assert-rect right 400 0 100 40 "filler no-spacing right")))

(%deftest test-filler-pushes-siblings-with-spacing
  (let* ((left (make-instance 'color-rect :min-width 100 :min-height 40))
         (middle (make-instance 'filler :min-width 0 :min-height 0 :expand-x t :expand-y nil))
         (right (make-instance 'color-rect :min-width 100 :min-height 40))
         (box (make-instance 'hbox :children (list left middle right) :spacing 10))
         (root (make-instance 'window :width 500 :height 100 :child box)))
    (%assert-min-size box 220 40 "filler spacing min-size")
    (layout root (make-rect :x 0 :y 0 :width 500 :height 100))
    (%assert-rect left 0 0 100 40 "filler spacing left")
    (%assert-rect middle 110 0 280 0 "filler spacing middle")
    (%assert-rect right 400 0 100 40 "filler spacing right")))

(%deftest test-multiple-fillers-split-equally
  (let* ((left (make-instance 'color-rect :min-width 100 :min-height 20))
         (fill-a (make-instance 'filler :min-width 0 :min-height 0 :expand-x t :expand-y nil))
         (fill-b (make-instance 'filler :min-width 0 :min-height 0 :expand-x t :expand-y nil))
         (right (make-instance 'color-rect :min-width 100 :min-height 20))
         (box (make-instance 'hbox :children (list left fill-a fill-b right) :spacing 0))
         (root (make-instance 'window :width 500 :height 100 :child box)))
    (%assert-min-size box 200 20 "multiple fillers min-size")
    (layout root (make-rect :x 0 :y 0 :width 500 :height 100))
    (%assert-rect left 0 0 100 20 "multiple fillers left")
    (%assert-rect fill-a 100 0 150 0 "multiple fillers A")
    (%assert-rect fill-b 250 0 150 0 "multiple fillers B")
    (%assert-rect right 400 0 100 20 "multiple fillers right")))

(%deftest test-hbox-with-images-and-filler
  (let* ((left (make-instance 'image :surface '(:width 20 :height 10)))
         (fill (make-instance 'filler :min-width 0 :min-height 0 :expand-x t :expand-y nil))
         (right (make-instance 'image :surface '(:width 30 :height 10)))
         (row (make-instance 'hbox :children (list left fill right) :spacing 0))
         (root (make-instance 'window :width 200 :height 40 :child row)))
    (layout root (make-rect :x 0 :y 0 :width 200 :height 40))
    (%assert-equal (rect-width (widget-layout-rect left)) 20 "left image keeps native width")
    (%assert-equal (rect-width (widget-layout-rect right)) 30 "right image keeps native width")
    (%assert-equal (rect-width (widget-layout-rect fill)) 150 "filler absorbs extra width")))
